### ISSUE TITLE
Always show access denied

### ISSUE THREAD

**Issue by hiteshj** [TheLordBaski/Amazon-mws-nodejs-sdk#2]
Hello Dear,

I have install this sdk and set up accordingly. But whenever i want to access any service then response is "Access Denied".

**Comment by TheLordBaski** [comment]
Can you paste some code here so I can help you ? :)

**Comment by hiteshj** [comment]
Thanks for your reply.

I have found the issue that is mws auth token which was not consider in mws.js file. Now code is working fine with api.

**Comment by TheLordBaski** [comment]
Yeah MWS  AUTH token should be in config file.
