### ISSUE TITLE
GetLowestPricedOffersForASIN returns invalid MarketplaceID

### ISSUE THREAD

**Issue by ParulShukla90** [TheLordBaski/Amazon-mws-nodejs-sdk#5]
Hi,
I am using your module to create a repricing application and m trying to get GetLowestPricedOffersForASIN using your module and it returns the following error:

<ErrorResponse xmlns="http://mws.amazonservices.com/schema/Products/2011-10-01">
    <Error status="ClientError">
        <Code>InvalidParameterValue</Code>
        <Type>Sender</Type>
        <Message>Invalid MarketplaceId</Message>
    </Error>
    <ResponseMetadata>
          <RequestId>2ff4898c-ba6a-4cf6-b242-0d4a22b948f0</RequestId>
    </ResponseMetadata>
</ErrorResponse>

I have cross checked all the details required while making request (including MarketplaceId), all of them are correct. If I make a request with the same details and credentials via scratchpad it is working fine. I am not able to understand why am I getting this error.  Please help me out here as I am stuck on this issue.

**Comment by TheLordBaski** [comment]
Hi @ParulShukla90 
Can you send me your whole body of request ? I can't test it myself because my mws credentials are invalid for now :D .

**Comment by ParulShukla90** [comment]
Hi @TheLordBaski,
Thanks for looking into the matter. Please give me your email id so that I can send you the details. 
Thanks :)
