### ISSUE TITLE
Readme examples aren't working

### ISSUE THREAD

**Issue by jvgeee** [TheLordBaski/Amazon-mws-nodejs-sdk#7]
Two issues in the readme:
- you need to load in the module with `var mws = require("mws-nodejs").mws;`, not `amazon-mws-nodejs`.
- The examples (GetServiceStatus specifically) generates an XML response rather than JSON, which causes errors in parsing that data.

**Comment by dakoller** [comment]
That's how the GetServiceStatus works

var XML = require('pixl-xml')

mws.products.GetServiceStatus(config, true, function (err, data) {
    var data2 = XML.parse(data);
    console.log("GetServiceStatus:");
    console.log(data2.GetServiceStatusResult);
    console.log("\n");

});
